### ISSUE TITLE
Implementing feedbacks

### ISSUE THREAD

**Issue by PoojithaGowthaman** [ubco-mds-2020-labs/dashboard-project---r-data551_g5#2]
* Changing to lighter theme
* Implementing tabs
* Reworking on graphs

**Comment by Sowmya-Chenthi-Kumar** [comment]
A lighter theme was adopted. 
Two tabs were added - Overview tab and factors tab 
Improved on the age and sex-based factors graph

**Comment by Sowmya-Chenthi-Kumar** [comment]
Reworked on beautifying the graphs
